#Author: Sergio Perez Sanz(sps169@outlook.es)

print("Piensa, apunta o escribe en una hoja de papel tu talla de zapato y pulsa enter.")
input()
print("Multiplicalo por 5 y pulsa enter.")
input()
print("Sumale 50 y pulsa enter.")
input()
print("Multiplicalo por 20 y pulsa enter")
input()
print("Sumale 1022 y pulsa enter")
input()
print("Restale tu año de nacimiento y pulsa enter")
input()
print("Cual es tu resultado? Introduce el numero final y pulsa enter")
finalNum = int(input())
talla = str(int(finalNum / 100))
edad = str(finalNum % 100)
print("Tu talla de zapatos es "+ talla + " y este año cumples " + edad + " años.")
